"""Build data/players.js for FCdle.

Inputs (place both in scripts/input/):
  players_raw.csv  EA SPORTS FC 27 Player Ratings by MikeDPad (Kaggle), the full
                   source export. Used for strength and first/last names.
  players.csv      The cleaned men's table from the Footle project
                   (github.com/Akif-b-Atif/Football-wordle, data/players.csv),
                   which adds each player's age at the snapshot date and
                   nationality continent.

Output:
  data/players.js  A single `const RAW = [...]` array the game loads.

The pool is outfield players (no goalkeepers) in the top flight of the
Premier League, LaLiga, Bundesliga, Serie A and Ligue 1. Row order matters:
the daily puzzle picks a player by index, so rebuilding with different data
changes which card each day uses.

Usage:
  python3 scripts/build_data.py
"""

import csv
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INPUT = ROOT / "scripts" / "input"
OUT = ROOT / "data" / "players.js"

LEAGUES = {
    "Premier League": "Premier League",
    "LALIGA EA SPORTS": "LaLiga",
    "Bundesliga": "Bundesliga",
    "Serie A Enilive": "Serie A",
    "Ligue 1 McDonald's": "Ligue 1",
}
FACE_STATS = ["pace", "shooting", "passing", "dribbling", "defending", "physicality"]


def main():
    raw = {r["player_id"]: r for r in csv.DictReader(open(INPUT / "players_raw.csv", encoding="utf-8"))}
    rows = []
    for r in csv.DictReader(open(INPUT / "players.csv", encoding="utf-8")):
        if r["primary_position"] == "GK" or r["league_name"] not in LEAGUES:
            continue
        w = raw[r["player_id"]]
        full = f'{w["first_name"]} {w["last_name"]}'.strip() or r["long_name"]
        alias = r["long_name"] if r["long_name"].replace('"', "") != full else ""
        row = [
            r["short_name"], r["long_name"], int(r["overall"]), r["primary_position"],
            r["club_name"], LEAGUES[r["league_name"]], r["nationality_name"],
            r["nationality_continent"], int(r["age"]),
            *[int(r[k]) for k in FACE_STATS], int(w["power_strength"]), full,
        ]
        if alias:
            row.append(alias)
        rows.append(row)

    # Two players sharing a card name get their full name instead.
    counts = Counter(row[0] for row in rows)
    for row in rows:
        if counts[row[0]] > 1:
            row[0] = row[1]
    data = [[row[0]] + row[2:] for row in rows]

    header = (
        "// Generated by scripts/build_data.py. Do not edit by hand.\n"
        "// Row: [name, ovr, pos, club, league, nation, continent, age, "
        "pac, sho, pas, dri, def, phy, str, full name, alias]\n"
    )
    OUT.write_text(header + "const RAW = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n", encoding="utf-8")
    print(f"Wrote {len(data)} players to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
